#!/usr/bin/env bash

#-----------------------------------------------------------------------
# run
# Author: Bob Dondero
#-----------------------------------------------------------------------

if [ $# -lt 1 ]
then
   echo "Usage: $0 class [arguments]"
   exit 1
fi

cp=.
for jarfile in *.jar; do
   cp=$cp:$jarfile
done

java -cp $cp "$@"
